### ISSUE TITLE
Add support for actuation component types

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/oisp-sdk-python#11]
The `add_component_type` method in `Client` does not work as some parameters are missing.

**Comment by oguzcankirmemis** [comment]
Waiting eagerly for this feature, so that I can do everything without even opening the dashboard!

**Comment by arkocal** [comment]
This is actually fixed by #13. The method needs to be documented, but I would rather do it after we review the API.

Rule creation still is not implemented though,

**Comment by arkocal** [comment]
@oguzcankirmemis see example at: https://gist.github.com/arkocal/771479de31240d5dc17f83f761bec4f3
