### ISSUE TITLE
Missing Design guideline

### ISSUE THREAD

**Issue by maxdos64** [Open-IoT-Service-Platform/oisp-sdk-python#15]
There should be a general design guideline for client apis 
Every OpenSource software which motivates collaboration should have one

**Comment by arkocal** [comment]
CONTRIBUTING on project root gives instructions on getting started and encourages to get in contact with repo owners before implementing changes. General design guideline would not be relevant to the python-sdk. Moving this to https://github.com/Open-IoT-Service-Platform/platform-launcher .
